// Structured analysis produced by the LLM in Phase 2
export interface PromptAnalysis {
  domain: string;
  risk_level: "low" | "medium" | "high" | "critical";
  architectural_impact: "none" | "low" | "medium" | "high";
  product_ambiguity: "none" | "low" | "medium" | "high";
  surfaced_concerns: string[];
}

export type EntryType = "decision" | "wont_do" | "table" | "branch" | "rollback" | "observation";

// A clarification question generated by the LLM, before it's persisted
export interface GeneratedQuestion {
  text: string;
  category: "architectural" | "product" | "infra" | "compliance" | "ux";
  risk_level: "low" | "medium" | "high" | "critical";
  // true when risk_level is high/critical AND the developer marks it unanswerable locally
  should_escalate: boolean;
  // LLM hint at which Stoa entry type this question's answer will likely be
  suggested_entry_type: EntryType;
}

// Shared shape for decision rows in API responses (excludes raw embedding)
export interface DecisionRow {
  decision_id: string;
  hex_id: string;
  entry_type: string;
  question_text: string;
  answer: string;
  alternatives_considered: string | null;
  rationale: string | null;
  reopen_condition: string | null;
  supersedes_id: string | null;
  reviewer_slack_id: string | null;
  linked_files: string[];
  linked_repo: string | null;
  repo_id: string | null;
  created_at: string;
}
